encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create_new_page", views.create_new_page, name="create_new_page"),
    path("edit", views.edit, name="edit"),
    path("update", views.update, name="update"),
    path("random_page", views.random_page, name="random_page"),
    path("<str:title>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

import markdown2
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# this funtion takes a parameter entered in the url the parameter should be the title of one of the entrys
def entry(request, title):
    # if the parameter is not the titles of one of the entries then throw an error message
    if not util.get_entry(title):
        return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": "Entry does not exist"
        })
    # if its is one of the entries then dispalay the information
    return render(request, "encyclopedia/entry.html", {
    "title": title,
    "content": markdown2.markdown(util.get_entry(title))
    })

def search(request):
    # as soon as user posts search request
    if request.method == "POST":
        # place user input into the title varuble
        title = request.POST["q"]
        # if the title does not match any of the titles saved
        if not util.get_entry(title):
            # then pull the list of all the titles saved
            list = util.list_entries()
            result = []
            # loop through them
            for item in list:
                # if one of the items kinda match what where looking for then save them in the result list
                if title in item:
                    result.append(item)
            # if the result list is empty then throw an error
            if not result:
                return render(request, "encyclopedia/search.html",{
                "message": "No Match Found",
                "result": list
                })
            # otherwise return the list
            return render(request, "encyclopedia/search.html",{
            "message": "Search results",
            "result" : result
            })

        # redirect them to the page with the results of the search request
        return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"title":request.POST["q"]}))
    return render(request, "encyclopedia/search.html")

# created form
class new_page(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class':'title'}))
    content = forms.CharField(widget=forms.Textarea)

def create_new_page(request):
    # if user posted data
    if request.method == "POST":
        # take the data user submitted and save it in form
        form = new_page(request.POST)
        # make sure data is valid
        if form.is_valid():

            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            # make sure title doen't exixt yet
            if not util.get_entry(title):
                # save content
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"title":title}))

            else:
                # if it does exixt then render error message
                return render(request, "encyclopedia/error.html",{
                "error": "Title already exists"
                })


        else:
            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/create_new_page.html", {
                "form": form
            })
    # return blank form
    return render(request, "encyclopedia/create_new_page.html",{
    "form": new_page()
    })

def edit(request):
    # as soon as user posts search request
    if request.method == "POST":
        # place user input into the title varuble
        title = request.POST["title"]
        # derect user to page where they can edit the content
        return render(request, "encyclopedia/edit.html", {
        "title": title,
        "content": util.get_entry(title)
        })

    return render(request, "encyclopedia/error.html",{
    "error": "Select the page you want to edit"
    })

def update(request):
    # if user submits changes
    if request.method == "POST":
        # save the changes
        util.save_entry(request.POST["title"], request.POST["content"])
        # direct user to the page with the new content
        return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"title":request.POST["title"]}))

    return render(request, "encyclopedia/error.html",{
    "error": "Select the page you want to update"
    })

def random_page(request):
    # redirect user to a random page
    return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"title":random.choice(util.list_entries())}))

encyclopedia/templates/encyclopedia/create_new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    create new page
{% endblock %}

{% block body %}
  <h1>create new page</h1>
  <form action="{% url 'encyclopedia:create_new_page'%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="submit">
  </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
  <h1>Edit Page</h1>
  <form action="{% url 'encyclopedia:update'%}" method="post">
    {% csrf_token %}
    <label for="title">Title:</label>
    <input type="text" name="title" id="title" value="{{ title }}" class="title">
    <label for="content">Content:</label>
    <textarea name="content">{{ content }}</textarea>
    <input type="submit" name="submit">
  </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
  <h1>{{ content|safe }}</h1>
  <form action="{% url 'encyclopedia:edit'%}" method="post">
    {% csrf_token %}
    <input type="hidden" name="title" value="{{title}}">
    <input type="submit" name="edit" value="Edit">
  </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
  <h3>{{ error }}</h3>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry%}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                  {% csrf_token %}
                  <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:create_new_page' %}">Create New Page</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}

  <h1>{{message}}</h1>
  {%for title in result%}
    <li><a href="{% url 'encyclopedia:entry' title=title%}">{{ title }}</a></li>
  {% endfor %}
{% endblock %}